POST http://localhost:5000/orchestration/orders
Content-Type: application/json

{
  "orderDetails": "Burger",
  "address": "Palace Square, 2"
}

###

POST http://localhost:5000/orchestration/orders/423c53af-0e3f-4659-820b-75b1c6bac2ba/accept
Content-Type: application/json

{
}

###

POST http://localhost:5000/choreography/orders
Content-Type: application/json

{
  "orderDetails": "Pizza",
  "address": "Palace Square, 2"
}

###

POST http://localhost:5000/choreography/orders/d821524b-8739-44bb-9023-b0a39a496f41/accept
Content-Type: application/json

{
}

###